pages:
  stage: deploy
  services:
    - node:latest
  image: node:latest
  script:
    - mkdir .public
    - npm install
    - npm run build
    - cp -r docs .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
